eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true
  instance:
    prefer-ip-address: true
server:
  port: 9003