eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true
  instance:
    prefer-ip-address: true

server:
  port: 8080
spring:
  application:
    name: getaway-server
  cloud:
    gateway:
      routes:
      - id: CAR-SALE
      - id: USER-MICRO-SERVICE
        uri: lb://USER-MICRO-SERVICE
        predicates:
          - Path=/us/**
        filters:
          - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
