server:
  port: 8081

spring:
  cloud:
    config:
      discovery:
        service-id: Config-Server
      server:
        git:
          uri: 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true
  instance:
    prefer-ip-address: true